<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>Veloce.Knowledgebase</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Veloce.Knowledgebase.Application.Contracts\Veloce.Knowledgebase.Application.Contracts.csproj" />
    <ProjectReference Include="..\Veloce.Knowledgebase.Domain.Shared\Veloce.Knowledgebase.Domain.Shared.csproj" />
    <ProjectReference Include="..\Veloce.Knowledgebase.Domain\Veloce.Knowledgebase.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Ride\" />
    <Folder Include="Services\User\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

</Project>
