// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Veloce.Knowledgebase;

#nullable disable

namespace Veloce.Knowledgebase.Migrations
{
    [DbContext(typeof(VeloceDbContext))]
    partial class VeloceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Veloce.Knowledgebase.Services.Ride.RideEntity", b =>
                {
                    b.Property<Guid>("RideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AverageSpeed")
                        .HasColumnType("numeric");

                    b.Property<string>("CoordinateHighestLeanAngleLeft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoordinateHighestLeanAngleRight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CoordinateHighestSpeed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Distance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Duration")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HighestGForce")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HighestLeanAngleLeft")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HighestLeanAngleRight")
                        .HasColumnType("numeric");

                    b.Property<decimal>("HighestSpeed")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RideId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("Veloce.Knowledgebase.Services.Ride.RidePointEntity", b =>
                {
                    b.Property<Guid>("RidePointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Coordinate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GForce")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Lean")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RideId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Speed")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RidePointId");

                    b.HasIndex("RideId");

                    b.ToTable("RidePoints");
                });

            modelBuilder.Entity("Veloce.Knowledgebase.Services.User.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GForceRecord")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LeanRecordLeft")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LeanRecordRight")
                        .HasColumnType("numeric");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("SpeedRecord")
                        .HasColumnType("numeric");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Veloce.Knowledgebase.Services.Vehicle.VehicleEntity", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VehicleId");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Veloce.Knowledgebase.Services.Ride.RideEntity", b =>
                {
                    b.HasOne("Veloce.Knowledgebase.Services.User.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veloce.Knowledgebase.Services.Vehicle.VehicleEntity", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Veloce.Knowledgebase.Services.Ride.RidePointEntity", b =>
                {
                    b.HasOne("Veloce.Knowledgebase.Services.Ride.RideEntity", null)
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Veloce.Knowledgebase.Services.Vehicle.VehicleEntity", b =>
                {
                    b.HasOne("Veloce.Knowledgebase.Services.User.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
